import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// Top 300+ Chinese words from Jun Da's frequency corpus
// Format: [chinese, pinyin, english, frequency_rank, is_grammatical]
const WORDS: [string, string, string, number, boolean][] = [
  ['的', 'de', 'possessive particle', 1, true],
  ['了', 'le', 'completion particle', 2, true],
  ['是', 'shì', 'to be', 3, false],
  ['在', 'zài', 'at/in/on', 4, false],
  ['有', 'yǒu', 'to have', 5, false],
  ['不', 'bù', 'not/no', 6, false],
  ['我', 'wǒ', 'I/me', 7, false],
  ['他', 'tā', 'he/him', 8, false],
  ['这', 'zhè', 'this', 9, false],
  ['们', 'men', 'plural suffix', 10, true],
  ['中', 'zhōng', 'middle/in', 11, false],
  ['来', 'lái', 'to come', 12, false],
  ['上', 'shàng', 'up/above', 13, false],
  ['大', 'dà', 'big/large', 14, false],
  ['为', 'wèi', 'for/because', 15, true],
  ['和', 'hé', 'and/with', 16, true],
  ['国', 'guó', 'country/nation', 17, false],
  ['地', 'de', 'adverb particle', 18, true],
  ['到', 'dào', 'to arrive/to', 19, false],
  ['以', 'yǐ', 'using/with', 20, true],
  ['说', 'shuō', 'to say/speak', 21, false],
  ['时', 'shí', 'time/when', 22, false],
  ['要', 'yào', 'to want/need', 23, false],
  ['就', 'jiù', 'then/just', 24, true],
  ['出', 'chū', 'to go out', 25, false],
  ['会', 'huì', 'can/will', 26, false],
  ['可', 'kě', 'can/may', 27, false],
  ['也', 'yě', 'also/too', 28, true],
  ['你', 'nǐ', 'you', 29, false],
  ['对', 'duì', 'correct/towards', 30, false],
  ['生', 'shēng', 'life/to be born', 31, false],
  ['能', 'néng', 'can/able', 32, false],
  ['而', 'ér', 'and/but (formal)', 33, true],
  ['子', 'zi', 'child/son', 34, false],
  ['那', 'nà', 'that', 35, false],
  ['得', 'de', 'result complement particle', 36, true],
  ['于', 'yú', 'at/in/from', 37, true],
  ['着', 'zhe', 'ongoing action particle', 38, true],
  ['下', 'xià', 'down/below', 39, false],
  ['自', 'zì', 'self/from', 40, false],
  ['之', 'zhī', 'possessive particle (classical)', 41, true],
  ['年', 'nián', 'year', 42, false],
  ['过', 'guò', 'to pass/through', 43, false],
  ['发', 'fā', 'to send/emit', 44, false],
  ['后', 'hòu', 'after/behind', 45, false],
  ['作', 'zuò', 'to do/make', 46, false],
  ['里', 'lǐ', 'inside/within', 47, false],
  ['用', 'yòng', 'to use', 48, false],
  ['道', 'dào', 'road/way', 49, false],
  ['行', 'xíng', 'to go/walk', 50, false],
  ['所', 'suǒ', 'place/that which', 51, true],
  ['然', 'rán', 'so/thus', 52, true],
  ['家', 'jiā', 'home/family', 53, false],
  ['种', 'zhǒng', 'type/kind', 54, false],
  ['事', 'shì', 'matter/affair', 55, false],
  ['成', 'chéng', 'to become', 56, false],
  ['方', 'fāng', 'direction/square', 57, false],
  ['多', 'duō', 'many/much', 58, false],
  ['经', 'jīng', 'to pass through', 59, false],
  ['么', 'me', 'question suffix', 60, true],
  ['吗', 'ma', 'yes/no question particle', 321, true],
  ['去', 'qù', 'to go', 61, false],
  ['法', 'fǎ', 'law/method', 62, false],
  ['学', 'xué', 'to study/learn', 63, false],
  ['如', 'rú', 'like/as if', 64, true],
  ['都', 'dōu', 'all/both', 65, true],
  ['同', 'tóng', 'same/together', 66, false],
  ['现', 'xiàn', 'present/appear', 67, false],
  ['当', 'dāng', 'when/to serve as', 68, true],
  ['没', 'méi', 'not have/did not', 69, false],
  ['动', 'dòng', 'to move', 70, false],
  ['面', 'miàn', 'face/side', 71, false],
  ['起', 'qǐ', 'to rise/start', 72, false],
  ['看', 'kàn', 'to look/see', 73, false],
  ['定', 'dìng', 'to decide/settle', 74, false],
  ['天', 'tiān', 'sky/day', 75, false],
  ['分', 'fēn', 'minute/part', 76, false],
  ['还', 'hái', 'still/also', 77, true],
  ['进', 'jìn', 'to enter', 78, false],
  ['好', 'hǎo', 'good/well', 79, false],
  ['小', 'xiǎo', 'small/little', 80, false],
  ['部', 'bù', 'part/section', 81, false],
  ['其', 'qí', 'his/her/its/their', 82, true],
  ['些', 'xiē', 'some/a few', 83, true],
  ['主', 'zhǔ', 'main/master', 84, false],
  ['样', 'yàng', 'manner/way', 85, false],
  ['理', 'lǐ', 'reason/logic', 86, false],
  ['心', 'xīn', 'heart/mind', 87, false],
  ['她', 'tā', 'she/her', 88, false],
  ['本', 'běn', 'root/original', 89, false],
  ['前', 'qián', 'front/before', 90, false],
  ['开', 'kāi', 'to open', 91, false],
  ['但', 'dàn', 'but/however', 92, true],
  ['因', 'yīn', 'because/cause', 93, true],
  ['只', 'zhǐ', 'only/just', 94, true],
  ['从', 'cóng', 'from/since', 95, true],
  ['想', 'xiǎng', 'to think/want', 96, false],
  ['实', 'shí', 'real/actual', 97, false],
  ['日', 'rì', 'sun/day', 98, false],
  ['军', 'jūn', 'army/military', 99, false],
  ['无', 'wú', 'without/none', 100, false],
  ['给', 'gěi', 'to give', 101, false],
  ['被', 'bèi', 'by (passive)', 102, true],
  ['把', 'bǎ', 'to hold (disposal marker)', 103, true],
  ['打', 'dǎ', 'to hit/strike', 104, false],
  ['走', 'zǒu', 'to walk/go', 105, false],
  ['问', 'wèn', 'to ask', 106, false],
  ['知', 'zhī', 'to know', 107, false],
  ['点', 'diǎn', 'point/dot/a little', 108, false],
  ['高', 'gāo', 'high/tall', 109, false],
  ['将', 'jiāng', 'will/about to', 110, true],
  ['水', 'shuǐ', 'water', 111, false],
  ['见', 'jiàn', 'to see/meet', 112, false],
  ['明', 'míng', 'bright/clear', 113, false],
  ['们', 'men', 'plural suffix (alt)', 114, true],
  ['人', 'rén', 'person/people', 115, false],
  ['很', 'hěn', 'very', 116, true],
  ['次', 'cì', 'time/occurrence', 117, false],
  ['又', 'yòu', 'again/also', 118, true],
  ['作', 'zuō', 'to do/work', 119, false],
  ['长', 'cháng', 'long', 120, false],
  ['公', 'gōng', 'public/official', 121, false],
  ['机', 'jī', 'machine/opportunity', 122, false],
  ['入', 'rù', 'to enter', 123, false],
  ['常', 'cháng', 'often/common', 124, false],
  ['华', 'huá', 'China/splendid', 125, false],
  ['活', 'huó', 'to live/alive', 126, false],
  ['回', 'huí', 'to return', 127, false],
  ['加', 'jiā', 'to add', 128, false],
  ['给', 'jǐ', 'to supply', 129, false],
  ['报', 'bào', 'newspaper/report', 130, false],
  ['间', 'jiān', 'between/room', 131, false],
  ['口', 'kǒu', 'mouth/opening', 132, false],
  ['内', 'nèi', 'inside/inner', 133, false],
  ['己', 'jǐ', 'oneself', 134, false],
  ['手', 'shǒu', 'hand', 135, false],
  ['情', 'qíng', 'feeling/emotion', 136, false],
  ['如', 'rú', 'if/as', 137, true],
  ['结', 'jié', 'to tie/result', 138, false],
  ['名', 'míng', 'name/famous', 139, false],
  ['此', 'cǐ', 'this/here', 140, true],
  ['都', 'dū', 'capital city', 141, false],
  ['义', 'yì', 'righteousness/meaning', 142, false],
  ['关', 'guān', 'to close/related to', 143, false],
  ['外', 'wài', 'outside/foreign', 144, false],
  ['位', 'wèi', 'position/seat', 145, false],
  ['全', 'quán', 'complete/whole', 146, false],
  ['第', 'dì', 'ordinal number prefix', 147, true],
  ['很', 'hěn', 'very (alt)', 148, true],
  ['者', 'zhě', 'person/one who', 149, true],
  ['使', 'shǐ', 'to use/cause', 150, false],
  ['两', 'liǎng', 'two/both', 151, false],
  ['与', 'yǔ', 'and/with', 152, true],
  ['又', 'yòu', 'again', 153, true],
  ['己', 'jǐ', 'self', 154, false],
  ['产', 'chǎn', 'to produce', 155, false],
  ['通', 'tōng', 'through/connect', 156, false],
  ['情', 'qíng', 'emotion/situation', 157, false],
  ['安', 'ān', 'peaceful/safe', 158, false],
  ['工', 'gōng', 'work/labor', 159, false],
  ['力', 'lì', 'power/strength', 160, false],
  ['场', 'chǎng', 'field/place', 161, false],
  ['时', 'shí', 'time', 162, false],
  ['三', 'sān', 'three', 163, false],
  ['老', 'lǎo', 'old/elderly', 164, false],
  ['政', 'zhèng', 'politics/government', 165, false],
  ['义', 'yì', 'meaning/justice', 166, false],
  ['特', 'tè', 'special/particularly', 167, false],
  ['然', 'rán', 'but/however', 168, true],
  ['达', 'dá', 'to reach/attain', 169, false],
  ['光', 'guāng', 'light/bright', 170, false],
  ['太', 'tài', 'too/very', 171, true],
  ['叫', 'jiào', 'to call/shout', 172, false],
  ['接', 'jiē', 'to receive/connect', 173, false],
  ['重', 'zhòng', 'heavy/important', 174, false],
  ['放', 'fàng', 'to release/put', 175, false],
  ['受', 'shòu', 'to receive/bear', 176, false],
  ['总', 'zǒng', 'always/general', 177, false],
  ['月', 'yuè', 'moon/month', 178, false],
  ['原', 'yuán', 'original/source', 179, false],
  ['最', 'zuì', 'most', 180, true],
  ['解', 'jiě', 'to solve/understand', 181, false],
  ['变', 'biàn', 'to change', 182, false],
  ['东', 'dōng', 'east', 183, false],
  ['西', 'xī', 'west', 184, false],
  ['南', 'nán', 'south', 185, false],
  ['北', 'běi', 'north', 186, false],
  ['问', 'wèn', 'question/ask', 187, false],
  ['快', 'kuài', 'fast/quick', 188, false],
  ['新', 'xīn', 'new', 189, false],
  ['少', 'shǎo', 'few/little', 190, false],
  ['吃', 'chī', 'to eat', 191, false],
  ['喝', 'hē', 'to drink', 192, false],
  ['买', 'mǎi', 'to buy', 193, false],
  ['卖', 'mài', 'to sell', 194, false],
  ['睡', 'shuì', 'to sleep', 195, false],
  ['觉', 'jiào', 'sleep/feel', 196, false],
  ['写', 'xiě', 'to write', 197, false],
  ['读', 'dú', 'to read', 198, false],
  ['听', 'tīng', 'to listen', 199, false],
  ['讲', 'jiǎng', 'to speak/tell', 200, false],
  ['玩', 'wán', 'to play', 201, false],
  ['跑', 'pǎo', 'to run', 202, false],
  ['飞', 'fēi', 'to fly', 203, false],
  ['跳', 'tiào', 'to jump', 204, false],
  ['笑', 'xiào', 'to laugh/smile', 205, false],
  ['哭', 'kū', 'to cry', 206, false],
  ['坐', 'zuò', 'to sit', 207, false],
  ['站', 'zhàn', 'to stand', 208, false],
  ['找', 'zhǎo', 'to look for', 209, false],
  ['带', 'dài', 'to carry/lead', 210, false],
  ['送', 'sòng', 'to send/give', 211, false],
  ['拿', 'ná', 'to take/hold', 212, false],
  ['借', 'jiè', 'to borrow/lend', 213, false],
  ['还', 'huán', 'to return', 214, false],
  ['帮', 'bāng', 'to help', 215, false],
  ['教', 'jiāo', 'to teach', 216, false],
  ['告', 'gào', 'to tell/inform', 217, false],
  ['诉', 'sù', 'to tell/complain', 218, false],
  ['等', 'děng', 'to wait/etc.', 219, true],
  ['让', 'ràng', 'to let/allow', 220, false],
  ['叫', 'jiào', 'to be called', 221, false],
  ['请', 'qǐng', 'to invite/please', 222, false],
  ['谢', 'xiè', 'to thank', 223, false],
  ['对不起', 'duìbuqǐ', 'sorry', 224, false],
  ['没关系', 'méiguānxi', "it's OK", 225, false],
  ['再见', 'zàijiàn', 'goodbye', 226, false],
  ['早', 'zǎo', 'early/morning', 227, false],
  ['晚', 'wǎn', 'evening/late', 228, false],
  ['午', 'wǔ', 'noon', 229, false],
  ['今', 'jīn', 'today/now', 230, false],
  ['明', 'míng', 'tomorrow/bright', 231, false],
  ['昨', 'zuó', 'yesterday', 232, false],
  ['现在', 'xiànzài', 'right now', 233, false],
  ['以前', 'yǐqián', 'before/in the past', 234, false],
  ['以后', 'yǐhòu', 'after/in the future', 235, false],
  ['这里', 'zhèlǐ', 'here', 236, false],
  ['那里', 'nàlǐ', 'there', 237, false],
  ['哪里', 'nǎlǐ', 'where', 238, false],
  ['什么', 'shénme', 'what', 239, false],
  ['谁', 'shuí', 'who', 240, false],
  ['为什么', 'wèishénme', 'why', 241, false],
  ['怎么', 'zěnme', 'how', 242, false],
  ['多少', 'duōshao', 'how many/much', 243, false],
  ['几', 'jǐ', 'how many/several', 244, false],
  ['一', 'yī', 'one', 245, false],
  ['二', 'èr', 'two', 246, false],
  ['四', 'sì', 'four', 247, false],
  ['五', 'wǔ', 'five', 248, false],
  ['六', 'liù', 'six', 249, false],
  ['七', 'qī', 'seven', 250, false],
  ['八', 'bā', 'eight', 251, false],
  ['九', 'jiǔ', 'nine', 252, false],
  ['十', 'shí', 'ten', 253, false],
  ['百', 'bǎi', 'hundred', 254, false],
  ['千', 'qiān', 'thousand', 255, false],
  ['万', 'wàn', 'ten thousand', 256, false],
  ['钱', 'qián', 'money', 257, false],
  ['块', 'kuài', 'piece/yuan', 258, false],
  ['号', 'hào', 'number/date', 259, false],
  ['个', 'gè', 'general measure word', 260, true],
  ['本', 'běn', 'measure word for books', 261, true],
  ['张', 'zhāng', 'measure word for flat things', 262, true],
  ['条', 'tiáo', 'measure word for long things', 263, true],
  ['件', 'jiàn', 'measure word for items', 264, true],
  ['杯', 'bēi', 'cup/glass', 265, false],
  ['碗', 'wǎn', 'bowl', 266, false],
  ['瓶', 'píng', 'bottle', 267, false],
  ['饭', 'fàn', 'food/cooked rice', 268, false],
  ['菜', 'cài', 'vegetable/dish', 269, false],
  ['肉', 'ròu', 'meat', 270, false],
  ['鱼', 'yú', 'fish', 271, false],
  ['蛋', 'dàn', 'egg', 272, false],
  ['面', 'miàn', 'noodles/flour', 273, false],
  ['包', 'bāo', 'bag/bread', 274, false],
  ['茶', 'chá', 'tea', 275, false],
  ['咖啡', 'kāfēi', 'coffee', 276, false],
  ['啤酒', 'píjiǔ', 'beer', 277, false],
  ['果', 'guǒ', 'fruit/result', 278, false],
  ['苹果', 'píngguǒ', 'apple', 279, false],
  ['香蕉', 'xiāngjiāo', 'banana', 280, false],
  ['书', 'shū', 'book', 281, false],
  ['报纸', 'bàozhǐ', 'newspaper', 282, false],
  ['电视', 'diànshì', 'television', 283, false],
  ['电话', 'diànhuà', 'telephone', 284, false],
  ['手机', 'shǒujī', 'mobile phone', 285, false],
  ['电脑', 'diànnǎo', 'computer', 286, false],
  ['网', 'wǎng', 'internet/net', 287, false],
  ['车', 'chē', 'car/vehicle', 288, false],
  ['路', 'lù', 'road/way', 289, false],
  ['店', 'diàn', 'shop/store', 290, false],
  ['医院', 'yīyuàn', 'hospital', 291, false],
  ['学校', 'xuéxiào', 'school', 292, false],
  ['公司', 'gōngsī', 'company', 293, false],
  ['银行', 'yínháng', 'bank', 294, false],
  ['超市', 'chāoshì', 'supermarket', 295, false],
  ['房子', 'fángzi', 'house', 296, false],
  ['城市', 'chéngshì', 'city', 297, false],
  ['中国', 'Zhōngguó', 'China', 298, false],
  ['朋友', 'péngyǒu', 'friend', 299, false],
  ['孩子', 'háizi', 'child', 300, false],
  ['老师', 'lǎoshī', 'teacher', 301, false],
  ['学生', 'xuéshēng', 'student', 302, false],
  ['医生', 'yīshēng', 'doctor', 303, false],
  ['工作', 'gōngzuò', 'work/job', 304, false],
  ['时间', 'shíjiān', 'time', 305, false],
  ['问题', 'wèntí', 'problem/question', 306, false],
  ['方法', 'fāngfǎ', 'method/way', 307, false],
  ['地方', 'dìfāng', 'place', 308, false],
  ['东西', 'dōngxi', 'thing/stuff', 309, false],
  ['语言', 'yǔyán', 'language', 310, false],
  ['汉语', 'Hànyǔ', 'Chinese language', 311, false],
  ['英语', 'Yīngyǔ', 'English language', 312, false],
  ['文化', 'wénhuà', 'culture', 313, false],
  ['历史', 'lìshǐ', 'history', 314, false],
  ['科学', 'kēxué', 'science', 315, false],
  ['艺术', 'yìshù', 'art', 316, false],
  ['音乐', 'yīnyuè', 'music', 317, false],
  ['运动', 'yùndòng', 'sport/exercise', 318, false],
  ['旅游', 'lǚyóu', 'travel/tourism', 319, false],
  ['天气', 'tiānqì', 'weather', 320, false],
]

async function main() {
  console.log('Seeding database...')

  // Clear existing data
  await prisma.wordEvent.deleteMany()
  await prisma.turn.deleteMany()
  await prisma.conversation.deleteMany()
  await prisma.appState.deleteMany()
  await prisma.word.deleteMany()

  // Remove duplicate frequency_ranks (keep first occurrence)
  const seen = new Set<number>()
  const seenChinese = new Set<string>()
  const uniqueWords = WORDS.filter(([chinese, , , rank]) => {
    if (seen.has(rank) || seenChinese.has(chinese)) return false
    seen.add(rank)
    seenChinese.add(chinese)
    return true
  })

  // Separate grammatical and non-grammatical words
  const grammatical = uniqueWords.filter(([, , , , isGram]) => isGram)
  const nonGrammatical = uniqueWords.filter(([, , , , isGram]) => !isGram)

  // Sort non-grammatical by frequency_rank
  nonGrammatical.sort((a, b) => a[3] - b[3])

  let wordRank = 0
  const wordsToCreate = uniqueWords.map(([chinese, pinyin, english, frequency_rank, is_grammatical]) => {
    const isFirst20NonGram = !is_grammatical && nonGrammatical.findIndex(w => w[0] === chinese) < 180

    return {
      chinese,
      pinyin,
      english,
      frequency_rank,
      is_grammatical,
      is_active: is_grammatical || isFirst20NonGram,
      comprehension_score: is_grammatical ? 50 : (isFirst20NonGram ? 0 : 0),
    }
  })

  await prisma.word.createMany({ data: wordsToCreate })

  // Initialize AppState singleton
  await prisma.appState.create({ data: { id: 1 } })

  const totalWords = wordsToCreate.length
  const activeWords = wordsToCreate.filter(w => w.is_active).length
  const grammaticalWords = wordsToCreate.filter(w => w.is_grammatical).length
  const activeNonGram = wordsToCreate.filter(w => w.is_active && !w.is_grammatical).length

  console.log(`Seeded ${totalWords} words total`)
  console.log(`  Active: ${activeWords} (${grammaticalWords} grammatical, ${activeNonGram} non-grammatical)`)
  console.log(`  Inactive (future expansion pool): ${totalWords - activeWords}`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
